trigger: none

pool: shiva-pool

stages:
  - stage: Build_stage
    jobs:
    - job: 
      
      steps:
      
      - task: TerraformInstaller@1
        displayName: Terraform_install
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        displayName: Terraform_init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/todoapp_infra/dev'
          backendServiceArm: 'shiva-connection'
          backendAzureRmStorageAccountName: 'shivastg'
          backendAzureRmContainerName: 'shivacontainer'
          backendAzureRmKey: 'shiva.tfstate'

      - task: TerraformTask@5
        displayName: Terraform_fmt
        inputs:
          provider: 'azurerm'
          command: 'custom'
          outputTo: 'console'
          customCommand: 'fmt'
          environmentServiceNameAzureRM: 'shiva-connection'

      - task: TerraformTask@5
        displayName: Terraform_validate
        inputs:
          provider: 'azurerm'
          command: 'validate'